config/routes.rb
  Rails.application.routes.draw do
    root :to => 'static_pages#home'

    namespace :teacher_system do

      get 'add_teacher' => 'teachers#new'
      get 'addmin_top' => 'teachers#show'
      get 'teach_cource' => 'teachers#attendance'
      get 'teach_cource_index' => 'teachers#index'
      get 'login' => 'sessions#new'
      post 'login' => 'sessions#create'
      delete 'logout' => 'sessions#destroy'

      resources :teachers
      resources :cources, shallow: true do
         get 'show_tasks' => 'tasks#show'
         get 'index_attend_users'=>'cource#index_attend_users'
         resources :tasks do
            resources :answers
         end

      end
    end

    namespace :user_system do
      get 'add_student' => 'users#new'
      get 'attend_cource' => 'users#attendance'
      get 'login' => 'sessions#new'
      post 'login' => 'sessions#create'
      delete 'logout' => 'sessions#destroy'

      resources :users
      resources :cources
    end


    resource :cources
    get'attend_user' => 'cources#index_attend_users'

    get 'add_user' => 'static_pages#choice'

    get 'index_user_teacher' => 'disp_users#index'


    get 'add_cource' => 'cources#new'
    get 'index_cource' => 'cources#index'
    get 'show_cource' => 'cources#show'



  end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
  def choice
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/choice.html.erb
<%= link_to '教師を追加',teacher_system_add_teacher_path %>
<%= link_to '生徒を追加',new_teacher_system_teacher_path %>

app/views/static_pages/home.html.erb
<h1>添削システムロジック</h1>


<h2><%= link_to 'コースの追加', add_cource_path %></h2>
<h2><%= link_to 'コース一覧', index_cource_path  %></h2>
<h2><%= link_to 'ユーザーの追加',add_user_path %></h2>
<h2><%= link_to 'ログイン',index_user_teacher_path %></h2>