config/routes.rb
  Rails.application.routes.draw do
    root :to => 'static_pages#home'

    namespace :teacher_system do

      get 'add_teacher' => 'teachers#new'
      get 'addmin_top' => 'teachers#show'
      get 'teach_cource' => 'teachers#attendance'
      get 'teach_cource_index' => 'teachers#index'
      get 'login' => 'sessions#new'
      post 'login' => 'sessions#create'
      delete 'logout' => 'sessions#destroy'

      resources :teachers
      resources :cources, shallow: true do
         get 'show_tasks' => 'tasks#show'
         get 'index_attend_users'=>'cource#index_attend_users'
         resources :tasks do
            resources :answers
         end

      end
    end

    namespace :user_system do
      get 'add_student' => 'users#new'
      get 'attend_cource' => 'users#attendance'
      get 'login' => 'sessions#new'
      post 'login' => 'sessions#create'
      delete 'logout' => 'sessions#destroy'

      resources :users
      resources :cources
    end


    resource :cources
    get'attend_user' => 'cources#index_attend_users'

    get 'add_user' => 'static_pages#choice'

    get 'index_user_teacher' => 'disp_users#index'


    get 'add_cource' => 'cources#new'
    get 'index_cource' => 'cources#index'
    get 'show_cource' => 'cources#show'



  end

app/models/task.rb
# == Schema Information
#
# Table name: tasks
#
#  id         :integer          not null, primary key
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :integer
#  cource_id  :integer
#  teacher_id :integer
#  name       :string(255)
#  content    :string(255)
#

class Task < ActiveRecord::Base
  belongs_to :user
  belongs_to :cource, class_name: 'Cource',foreign_key: :cource_id
  belongs_to :teacher, class_name: 'Teacher', foreign_key: :teacher_id

  has_many :tasks
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def new
    @cource = current_user.cources.find(params[:cource_id])
    @task = Task.new
  end

  def create
    @cource = current_user.cources.where(id: params[:cource_id])
    teacher = current_user
    @task = current_user.tasks.build(task_params)
    if @task.save
      redirect_to @task
    else
      redirect_to root_url
    end
  end

  def show
    @task = current_user.tasks
  end



  def index
    @mytasks = current_user.tasks
  end

  

  def edit
  end

  def update
  end

  private
  def task_params
    params.require(:task).permit(:name,:content,:user_id,:cource_id)
  end
end

app/controllers/teacher_system/cources_controller.rb
class TeacherSystem::CourcesController < ApplicationController
  def new
    @cource = Cource.new
  end

  def show
    @cource = Cource.find(params[:id])
    @tasks = @cource.tasks
  end

  def create
    @cource = Cource.new(cource_params)
    redirect_to root_url if @cource.save
  end

  def index
    @cources = Cource.all
  end


  private
  def cource_params
    params.require(:cource).permit(:name,:description)
  end
end

app/controllers/teacher_system/sessions_controller.rb
class TeacherSystem::SessionsController < ApplicationController
  def new
  end

  def create
    user_or_teacher = params[:dist]
    if params[:dist] == 'true'
      teacher = Teacher.find(params[:id])
      login(teacher,true)
      redirect_to [:teacher_system, teacher]
    elsif params[:dist] == 'false'
      user = User.find(params[:id])
      login(user,false)
      redirect_to user
    else
      flash[:error] = 'エラーです'
      redirect_to root_url
    end
  end

  def destroy
    logout
    redirect_to root_url
  end
end

app/controllers/teacher_system/tasks_controller.rb
class TeacherSystem::TasksController < ApplicationController
  def new
    @cource = current_user.cources.find(params[:cource_id])
    @task = Task.new
  end

  def create
    @cource = current_user.cources.where(id: params[:cource_id])
    teacher = current_user
    @task = current_user.tasks.build(task_params)
    if @task.save
      redirect_to teacher_system_cource_show_tasks_path
    else
      redirect_to root_url
    end
  end

  def show
    @mytasks = current_user.tasks
    @mycource = current_user.cources
  end

  def index_cource
    @mycource = current_user.cources
    @mytasks = current_user.tasks
  end

  def index
    @mytasks = current_user.tasks
  end


  def edit
  end

  def update
  end

  private
  def task_params
    params.require(:task).permit(:name,:content,:user_id,:cource_id,)
  end
end

app/controllers/teacher_system/teachers_controller.rb
class TeacherSystem::TeachersController < ApplicationController
  def new
    @teacher = Teacher.new
  end

  def create
    @teacher = Teacher.new(teacher_params)
    if @teacher.save
      redirect_to root_url
    else
      render 'new'
    end
  end

  def show
    @cources = Cource.all
    @teacher = current_user
    if @teacher.cources
      @my_cource = current_user.cources
    end
  end

  def index
    @cources = current_user.cources
  end

  def attendance
    @teacher = current_user
    @teacher.cources << Cource.find(params[:id])
    redirect_to [:teacher_system, @teacher]
  end


  private
  def teacher_params
    params.require(:teacher).permit(:name)
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/teacher_system/tasks/_disp_task.html.erb
  <tr>
    <td><%=link_to disp_task.cource.name, teacher_system_task_path(:id => disp_task.id) %></td>
    <td><%= disp_task.name %></td>
    <td>公開中</td>
    <td><%= disp_task.created_at.strftime('%Y年%m月%d日')%></td>
  </tr>

app/views/teacher_system/tasks/_myCource.html.erb
  <tr>
  <td><%= myCource.name %></td>
  <td><%= @mytasks.where(cource_id: myCource.id).count %></td>
  <td><%= link_to '課題を登録する',new_teacher_system_cource_task_path(cource_id: myCource.id) %></td>
  <td><%= link_to '受講生一覧',attend_user_path(cource_id: myCource.id)%>
  </tr>

app/views/teacher_system/tasks/create.html.erb
 <h2>登録先講座⇨<%= @cource.name %></h2>

app/views/teacher_system/tasks/edit.html.erb
<h1>Tasks#edit</h1>
<p>Find me in app/views/tasks/edit.html.erb</p>

app/views/teacher_system/tasks/index.html.erb
<h2>課題一覧</h2>
<table border=1>
  <tr><th>講座名</th><th>課題名</th><th>状態</th><th>公開日</th></tr>
  <%= render partial: 'disp_task', collection: @mytasks %>
<table>

app/views/teacher_system/tasks/index_cource.html.erb
  <h2>担当講座一覧</h2>

  <table border=1>
  <tr><th>担当講座</th><th>登録課題数</th><th></th></tr></tr>
    <%= render partial:'myCource', collection: @mycource %>
  </table>

  <div>
    <%= link_to '課題一覧', disp_task_path %>
  </div>

app/views/teacher_system/tasks/new.html.erb
  <h2>登録先講座 ⇨ <strong><%= @cource.name %></strong></h2>

  <h2>登録情報</h2>
  <%= form_for([:teacher_system ,:cource, @task]) do |f| %>
  <%= f.label '課題名' %>
  <%= f.text_field :name %>

  <div>
    <%= f.label '課題内容（テキスト）' %>
  </div>
  <div>
    <%= f.text_area :content, size:'20x10' %>
  </div>
  <%= f.hidden_field :cource_id, :value => current_user.cources.find(params[:cource_id]).id %>
  <%= f.submit '登録する' %>
  <% end %>

app/views/teacher_system/tasks/show.html.erb
 <h2>担当講座一覧</h2>

  <table border=1>
    <tr><th>担当講座</th><th>登録課題数</th><th></th><th></th></tr>
    <%= render partial:'teacher_system/tasks/myCource', collection: @mycource%>
  </table>

  <div>
    <%= link_to '課題一覧', teacher_system_cource_tasks_path(cource_id: 3) %>
  </div>

app/views/teacher_system/tasks/update.html.erb
<h1>Tasks#update</h1>
<p>Find me in app/views/tasks/update.html.erb</p>