config/routes.rb
  Rails.application.routes.draw do
    root :to => 'static_pages#home'

    namespace :teacher_system do

      get 'add_teacher' => 'teachers#new'
      get 'addmin_top' => 'teachers#show'
      get 'teach_cource' => 'teachers#attendance'
      get 'teach_cource_index' => 'teachers#index'
      get 'login' => 'sessions#new'
      post 'login' => 'sessions#create'
      delete 'logout' => 'sessions#destroy'

      resources :teachers
      resources :cources, shallow: true do
         get 'show_tasks' => 'tasks#show'
         get 'index_attend_users'=>'cource#index_attend_users'
         resources :tasks do
            resources :answers
         end

      end
    end

    namespace :user_system do
      get 'add_student' => 'users#new'
      get 'attend_cource' => 'users#attendance'
      get 'login' => 'sessions#new'
      post 'login' => 'sessions#create'
      delete 'logout' => 'sessions#destroy'

      resources :users
      resources :cources
    end


    resource :cources
    get'attend_user' => 'cources#index_attend_users'

    get 'add_user' => 'static_pages#choice'

    get 'index_user_teacher' => 'disp_users#index'


    get 'add_cource' => 'cources#new'
    get 'index_cource' => 'cources#index'
    get 'show_cource' => 'cources#show'



  end

app/controllers/disp_users_controller.rb
class DispUsersController < ApplicationController
  def index
    @users = User.all
    @teachers = Teacher.all
  end
end

app/views/disp_users/_teacher.html.erb
    <tr><th><%= teacher.id %></th><td><%= teacher.name %></td>
    <td><%= link_to 'ログイン',teacher_system_login_path(:id => teacher.id,:dist => true), method: :post %></td></tr>

app/views/disp_users/_user.html.erb
    <tr><th><%= user.id %></th><td><%= user.name %></td>
    <td><%= link_to 'ログイン',user_system_login_path(:id => user.id,:dist => false), method: :post %></td></tr>

app/views/disp_users/index.html.erb
<div>
  <h3>ユーザー一覧</h3>
  <table border=1>
    <tr><th>ID</th><th>名前</th></tr>
    <%= render partial: 'user', collection: @users %>
  </table>
</div>

<div>
  <h3>先生一覧</h3>
  <table border=1>
    <tr><th>ID</th><th>名前</th></tr>
    <%= render partial: 'teacher', collection: @teachers %>
  </table>
</div>