config/routes.rb
  Rails.application.routes.draw do
    root :to => 'static_pages#home'

    namespace :teacher_system do

      get 'add_teacher' => 'teachers#new'
      get 'addmin_top' => 'teachers#show'
      get 'teach_cource' => 'teachers#attendance'
      get 'teach_cource_index' => 'teachers#index'
      get 'login' => 'sessions#new'
      post 'login' => 'sessions#create'
      delete 'logout' => 'sessions#destroy'

      resources :teachers
      resources :cources, shallow: true do
         get 'show_tasks' => 'tasks#show'
         get 'index_attend_users'=>'cource#index_attend_users'
         resources :tasks do
            resources :answers
         end

      end
    end

    namespace :user_system do
      get 'add_student' => 'users#new'
      get 'attend_cource' => 'users#attendance'
      get 'login' => 'sessions#new'
      post 'login' => 'sessions#create'
      delete 'logout' => 'sessions#destroy'

      resources :users
      resources :cources
    end


    resource :cources
    get'attend_user' => 'cources#index_attend_users'

    get 'add_user' => 'static_pages#choice'

    get 'index_user_teacher' => 'disp_users#index'


    get 'add_cource' => 'cources#new'
    get 'index_cource' => 'cources#index'
    get 'show_cource' => 'cources#show'



  end

app/models/cource.rb
# == Schema Information
#
# Table name: cources
#
#  id          :integer          not null, primary key
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  name        :string(255)
#  description :string(255)
#

class Cource < ActiveRecord::Base
  validates :name, length:{maximum: 10}, presence: true

  has_many :cource_users, class_name: 'CourceUser', foreign_key: :cource_id
  has_many :users, :through =>  :cource_users

  has_many :cource_teachers, class_name: 'cource_teacher', foreign_key: :cource_id
  has_many :teachers, :through =>  :cource_teachers

  has_many :tasks, class_name:'Task', foreign_key: :cource_id
end

app/controllers/cources_controller.rb
class CourcesController < ApplicationController
  def new
    @cource = Cource.new
  end

  def show
    @cource = Cource.find(params[:id])
    @tasks = @cource.tasks
    @user = current_user
  end

  def create
    @cource = Cource.new(cource_params)
    redirect_to root_url if @cource.save
  end

  def index_attend_users
    @this_cource = Cource.find(params[:cource_id  ])
    @attend_users = @this_cource.users
  end
  def index
    @cources = Cource.all
  end

  private
  def cource_params
    params.require(:cource).permit(:name,:description)
  end
end

app/controllers/teacher_system/cources_controller.rb
class TeacherSystem::CourcesController < ApplicationController
  def new
    @cource = Cource.new
  end

  def show
    @cource = Cource.find(params[:id])
    @tasks = @cource.tasks
  end

  def create
    @cource = Cource.new(cource_params)
    redirect_to root_url if @cource.save
  end

  def index
    @cources = Cource.all
  end


  private
  def cource_params
    params.require(:cource).permit(:name,:description)
  end
end

app/controllers/user_system/cources_controller.rb
class UserSystem::CourcesController < ApplicationController
  def new
    @cource = Cource.new
  end

  def show
    @cource = Cource.find(params[:id])
    @tasks = @cource.tasks
  end

  def create
    @cource = Cource.new(cource_params)
    redirect_to root_url if @cource.save
  end

  def index
    @cources = Cource.all
  end

  private
  def cource_params
    params.require(:cource).permit(:name,:description)
  end
end

app/helpers/cources_helper.rb
module CourcesHelper

  include SessionsHelper
  def attend_cource?(cource)
    return false if current_user.nil?
    current_user.cources.where(id: params[:id]).presence
  end
end

app/views/cources/_attend_user.html.erb
  <li><strong><%= attend_user.name %></strong></li>

app/views/cources/_cource.html.erb
<tr><td><%= link_to cource.name, show_cource_path(id: cource.id) %></td></tr>

app/views/cources/_tasks.html.erb
  <li><%= tasks.name %></li>
   <div>
    課題の提出
    <button>提出する！</button>
  </div>

app/views/cources/index.html.erb
<h2>コース一覧</h2>

<table border=1>
<tr><th>名前</th></tr>
<%= render partial: 'cource', collection: @cources %>
<table>

app/views/cources/index_attend_users.html.erb
  <h2>受講者一覧</h2>

<ul>
  <%= render partial: 'attend_user', collection: @attend_users %>
</ul>

app/views/cources/new.html.erb
<div>
  <%= form_for(@cource) do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>
  <div>
    <%= f.label :description %>
  </div>
  <div>
    <%= f.text_area :description, size:"30x20" %>
  </div>
    <%= f.submit 'コース作成' %>
  <% end %>
</div>

app/views/cources/show.html.erb
  <h1><%= @cource.name %></h1>
  <% if attend_cource?(@cource) %>

  <h2>レッスン内容</h2>
  ほげほげほげほげほげ
  <hr>
  <h2>先生からの課題</h2>
  <div>
  <ul>
    <%= render partial:'tasks' , collection: @tasks%>
  </ul>
  </div>
 
  <% else %>
     <div>
      <h2>講座内容</h2>
      <p><%= simple_format(h(@cource.description))%></p>
    </div>
    <div>
      <% if current_user %>
          <%= link_to 'この講座を受講する',user_system_attend_cource_path(cource_id: @cource.id) %>
      <% end %>
    </div>
  <% end %>